sudo: false
language: python
env:
  - ASSIGNMENT=assignment9
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -c conda-forge opencv scikit-image numpy matplotlib notebook
  - pip install -q nose2
  - "curl -H \"Authorization: token ${GH_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' -O --location \"https://api.github.com/repos/PGE383-HPC/${ASSIGNMENT}/contents/test.py\""
  - "curl -H \"Authorization: token ${GH_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' -O --location \"https://api.github.com/repos/PGE383-HPC/${ASSIGNMENT}/contents/ss_plot_gold.png\""
script:
  - 'if [ ! -f "./${ASSIGNMENT}.py" ]; then
        jupyter nbconvert --to python ${ASSIGNMENT}.ipynb;
     fi'
  - nose2

after_success:
    - docker pull johntfoster/texlive
    #- python -c 'import matplotlib; matplotlib.use("pgf"); pgf_with_latex = {"pgf.texsystem": "docker run --rm -it johntfoster/texlive pdflatex"}; matplotlib.rcParams.update(pgf_with_latex); from assignment9 import Plotter; p = Plotter("data_1.dat"); p.plot_pgf("ss_plot")'
    - docker pull johntfoster/texlive
    - docker run --rm -it -v `pwd`:/var/texlive  johntfoster/texlive latexmk ${ASSIGNMENT}.tex
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git add ${ASSIGNMENT}.pdf
    - git commit -m "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER} [skip ci]"
    #- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master > /dev/null
