env:
  ASSIGNMENT: assignment9
on: push
jobs:
  conda:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
      - name: Fetch Tests 
        shell: bash -l {0}
        run: |
          curl \
          --header 'Authorization: token ${{secrets.PGE383_SECRET_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          -O --location "https://api.github.com/repos/PGE383-HPC/${ASSIGNMENT}/contents/test.py" \
      - name: Run Tests 
        shell: bash -l {0}
        run: |
          python test.py
      - name: Run LaTeX 
        shell: bash -l {0}
        run: |
          sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-extra texlive-latex-recommended texlive-pictures latexmk pgf
          python texify.py
          latexmk -pdf ${ASSIGNMENT}.tex
          git config user.name 'John T. Foster'
          git config user.email 'john.foster@utexas.edu'
          git add ${ASSIGNMENT}.pdf
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
